'use strict';

(function () {
  window.candyevents = {
    LOAD_CARDS: 'LOAD_CARDS',
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    EMPTY_BASKET: 'EMPTY_BASKET',
    NOT_EMPTY_BASKET: 'NOT_EMPTY_BASKET',
    SWITCH_TAB: 'SWITCH_TAB',
    CHANGE_FILTER: 'CHANGE_FILTER',
    CHANGE_SORT: 'CHANGE_SORT',
    CHANGE_PRICE: 'CHANGE_PRICE',
    SWITCH_ORDER_STATE: 'SWITCH_ORDER_STATE'
  };
})();
