'use strict';

(function () {
  window.candyevents = {
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    ADD_FROM_BASKET: 'ADD_FROM_BASKET',
    REQUEST_TO_BASKET: 'REQUEST_TO_BASKET',
    SWITCH_ORDER_STATE: 'SWITCH_ORDER_STATE',
    FILTER_INIT: 'FILTER_INIT',
    CHANGE_SORT: 'CHANGE_SORT',
    CHANGE_FILTER: 'CHANGE_FILTER',
    CHANGE_FILTER_PRODUCT: 'CHANGE_FILTER_PRODUCT',
    CHANGE_FILTER_PROPERTY: 'CHANGE_FILTER_PROPERTY',
    CHANGE_FILTER_PRICE: 'CHANGE_FILTER_PRICE',
    CHANGE_FILTER_MARK: 'CHANGE_FILTER_MARK'
  };
})();
